
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.io.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Himanshi
 */
public class fee_detail extends javax.swing.JFrame {

    private static void print(JTable.PrintMode printMode, MessageFormat header, MessageFormat footer) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form fee_detail
     */
    public fee_detail() {
        initComponents();
    }
    
          

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtsid1 = new javax.swing.JTextField();
        txtcid1 = new javax.swing.JTextField();
        txtamount1 = new javax.swing.JTextField();
        btnpay = new javax.swing.JButton();
        txtdate1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fee_record = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtname_search = new javax.swing.JTextField();
        txtsid_search = new javax.swing.JTextField();
        txtmobile_search = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtname1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtmobile1 = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("FEE DETAILS");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setText("Sid:");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setText("Cid:");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setText("Amount Received:");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel5.setText("Date Of Receive:");

        txtcid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcid1ActionPerformed(evt);
            }
        });

        txtamount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamount1ActionPerformed(evt);
            }
        });

        btnpay.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        btnpay.setText("PAY");
        btnpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpayActionPerformed(evt);
            }
        });

        txtdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdate1ActionPerformed(evt);
            }
        });

        fee_record.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "sid", "sname", "cid", "mobile"
            }
        ));
        fee_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fee_recordMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(fee_record);

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel6.setText("Name:");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel7.setText("Sid:");

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel8.setText("Mobile:");

        txtname_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtname_searchMouseClicked(evt);
            }
        });

        txtsid_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsid_searchMouseClicked(evt);
            }
        });
        txtsid_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsid_searchActionPerformed(evt);
            }
        });

        txtmobile_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtmobile_searchMouseClicked(evt);
            }
        });
        txtmobile_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobile_searchActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel9.setText("Sname:");

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel10.setText("Mobile:");

        btnsearch.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnprint.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        btnprint.setText("PRINT");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(124, 124, 124)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel10)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addComponent(btnpay, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtname1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsid1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcid1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmobile1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtamount1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnsearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtmobile_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtsid_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtname_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(545, 545, 545))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtname_search))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsid_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmobile_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(txtsid1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtname1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(txtmobile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtamount1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnpay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcid1ActionPerformed

    private void txtdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdate1ActionPerformed

    private void txtamount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamount1ActionPerformed

    private void fee_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fee_recordMouseClicked
        // TODO add your handling code here:
        int i=fee_record.getSelectedRow();
        //JOptionPane.showMessageDialog(this,""+i,"status",JOptionPane.
        TableModel model=fee_record.getModel();
        txtsid1.setText(model.getValueAt(i,0).toString());
        txtname1.setText(model.getValueAt(i,1).toString());
        txtcid1.setText(model.getValueAt(i,2).toString());
        txtmobile1.setText(model.getValueAt(i,3).toString());
        
        
    }//GEN-LAST:event_fee_recordMouseClicked

    private void txtsid_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsid_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsid_searchActionPerformed

    private void txtmobile_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobile_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobile_searchActionPerformed

    private void txtname_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtname_searchMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtname_searchMouseClicked

    private void txtsid_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsid_searchMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtsid_searchMouseClicked

    private void txtmobile_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmobile_searchMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtmobile_searchMouseClicked

    private void btnpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpayActionPerformed
        // TODO add your handling code here:
        try
        {
            String sname,mobile,date;
            int sid,cid,fee_rec;
           
            
            sname=txtname1.getText();
            mobile=txtmobile1.getText();
            date=txtdate1.getText();
            sid=Integer.parseInt(txtsid1.getText());
            cid=Integer.parseInt(txtcid1.getText());
            fee_rec=Integer.parseInt(txtamount1.getText());
            
            Connection con;
            Statement stmt;
            String uid="root";
            String pwd="";
            
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/final_project",uid,pwd);
            
            stmt=con.createStatement();
            String qry="INSERT INTO fee_details (sid,sname,cid,mobile,fee_received,date_of_receive) VALUES ("+sid+",'"+sname+"',"+cid+",'"+mobile+"',"+fee_rec+",'"+date+"')";
            
            //System.out.println(qry);
            stmt.executeUpdate(qry);
           
            /*table t=new table();
            t.setVisible(true);
            loaddata();
            this.dispose();*/
            JOptionPane.showMessageDialog(this,"Data Saved Successfully","Status",JOptionPane.INFORMATION_MESSAGE);
            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnpayActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
    {
        DefaultTableModel model=(DefaultTableModel)fee_record.getModel();
        fee_record.setModel(model);
        //
        model.setRowCount(0);
        Object row[]=new Object[4];
                try
                {
                    Connection con;
                    Statement stmt;
                    
                    String uid="root";
                    String pwd="";
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/final_project",uid,pwd);
                    stmt=con.createStatement();
                    String qry;
                    if(txtname_search.getText().length()>0 && txtsid_search.getText().length()>0 && txtmobile_search.getText().length()>0)
                    {
                      // System.out.println("SELECT student_details.sid,student_details.sname,course_applied.cid,student_details.mobile FROM student_details,course_applied WHERE student_details.sid=course_applied.sid , txtname_search LIKE '%"+txtname_search.getText()+"%' && txtsid_search LIKE %"+txtsid_search.getText()+"% && txtmobile_search LIKE '%"+txtmobile_search.getText()+"%'");
                     qry="SELECT student_details.sid,student_details.sname,course_applied.cid,student_details.mobile FROM student_details,course_applied WHERE student_details.sid=course_applied.sid AND sname LIKE '%"+txtname_search.getText()+"%' AND student_details.sid = "+txtsid_search.getText()+" AND mobile LIKE '%"+txtmobile_search.getText()+"%'";                        
                    }
                    else if(txtname_search.getText().length()==0 &&txtsid_search.getText().length()>0 &&txtmobile_search.getText().length()>0)
                    {
                     qry="SELECT student_details.sid,student_details.sname,course_applied.cid,student_details.mobile FROM student_details,course_applied WHERE student_details.sid=course_applied.sid AND student_details.sid = "+txtsid_search.getText()+" AND mobile LIKE '%"+txtmobile_search.getText()+"%'";            
                    }
                    else if(txtname_search.getText().length()>0 &&txtsid_search.getText().length()==0 &&txtmobile_search.getText().length()>0)
                    {
                    qry="SELECT student_details.sid,student_details.sname,course_applied.cid,student_details.mobile FROM student_details,course_applied WHERE student_details.sid=course_applied.sid AND sname LIKE '%"+txtname_search.getText()+"%' AND mobile LIKE '%"+txtmobile_search.getText()+"%'";            
                    }
                    else  if(txtname_search.getText().length()>0 &&txtsid_search.getText().length()>0 &&txtmobile_search.getText().length()==0)
                    {
                    qry="SELECT student_details.sid,student_details.sname,course_applied.cid,student_details.mobile FROM student_details,course_applied WHERE student_details.sid=course_applied.sid AND sname LIKE '%"+txtname_search.getText()+"%' AND student_details.sid = "+txtsid_search.getText()+"";            
                    }
                    else if(txtname_search.getText().length()>0 &&txtsid_search.getText().length()==0&&txtmobile_search.getText().length()==0)
                    {
                    qry="SELECT student_details.sid,student_details.sname,course_applied.cid,student_details.mobile FROM student_details,course_applied WHERE student_details.sid=course_applied.sid AND sname LIKE '%"+txtname_search.getText()+"%' ";                        
                    }
                    else if(txtname_search.getText().length()==0 &&txtsid_search.getText().length()==0 &&txtmobile_search.getText().length()>0)
                    {
                    qry="SELECT student_details.sid,student_details.sname,course_applied.cid,student_details.mobile FROM student_details,course_applied WHERE student_details.sid=course_applied.sid AND mobile LIKE '%"+txtmobile_search.getText()+"%' ";            
                                 
                    }
                    else if(txtname_search.getText().length()==0 &&txtsid_search.getText().length()>0 &&txtmobile_search.getText().length()==0)
                    {
                    qry="SELECT student_details.sid,student_details.sname,course_applied.cid,student_details.mobile FROM student_details,course_applied WHERE student_details.sid=course_applied.sid AND student_details.sid = "+txtsid_search.getText()+"";            
                                 
                    }
                    else
                    {
                    qry="SELECT student_details.sid,student_details.sname,course_applied.cid,student_details.mobile FROM student_details,course_applied WHERE student_details.sid=course_applied.sid ";            
                    }
                
                 ResultSet res=stmt.executeQuery(qry);
                    while(res.next())
                    {
                        row[0]=res.getInt("sid");
                        row[1]=res.getString("sname");
                        row[2]=res.getString("cid");
                        row[3]=res.getString("mobile");
                        model.addRow(row);
                    }
                }
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(this,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                }
    }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
/*
        MessageFormat header=new MessageFormat("Fee Reciept");
      MessageFormat footer=new MessageFormat("Page (0,number,integer)");
      try
      {
          fee_record.print(JTable.PrintMode.NORMAL,header,footer);
      }
      catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(this,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                }
        
        */

String str="<html>\n" +
"<head>\n" +
"<title></title>\n" +
"<style type=\"text/css\">\n" +
"*\n" +
"{\n" +
"padding:0;\n" +
"margin:0;\n" +
"}\n" +
"#wrapper\n" +
"{\n" +
"width:595px;\n" +
"height:274px;\n" +
"border:1px solid #000000;\n" +
"margin:0 auto;\n" +
"}\n" +
".company\n" +
"{\n" +
"background-color:#000000;\n" +
"color:#ffffff;\n" +
"text-align:center;\n" +
"padding:5px 0 5px 0;\n" +
"}\n" +
".para\n" +
"{\n" +
"text-align:center;\n" +
"font-weight:bold;\n" +
"\n" +
"}\n" +
"\n" +
".rec\n" +
"{\n" +
"text-align:center;\n" +
"border:1px solid #000000;\n" +
"width:200px;\n" +
"margin:10px auto;\n" +
"}\n" +
".dt\n" +
"{\n" +
"text-align:center;\n" +
"width:200px;\n" +
"margin:5px auto;\n" +
"font-weight:bold;\n" +
"}\n" +
".rc\n" +
"{\n" +
"padding:30px;\n" +
"\n" +
"}\n" +
".rc p\n" +
"{\n" +
"font-size:18px;\n" +
"\n" +
"}\n" +
".footer\n" +
"{\n" +
"background-color:#000000;\n" +
"color:#ffffff;\n" +
"text-align:center;\n" +
"}\n" +
"</style>\n" +
"</head>\n" +
"<body>\n" +
"<div id='wrapper'>\n" +
"<h2 class='company'>WIT'S TUTORIAL</h2>\n" +
"<p class='para'>Shankar Nagar, Raipur</p>\n" +
"<p class='para'>Mob. +91-94242-03068</p>\n" +
"<h2 class='rec'>Fee Receipt:</h2>\n" +
"<p class='dt'>Date of Payment:23-07-2018</p>\n" +
"<div class=\"rc\">\n" +
"<p>\n" +
"Received with thanks From <strong>"+txtname1.getText()+"</strong> a Sum of Rupees <strong>"+txtamount1.getText()+"</strong> Only\n" +
"by Cash mode of payment for the course <strong>CLASS </strong>\n" +
"</p>\n" +
"\n" +
"\n" +
"</div>\n" +
"\n" +
"\n" +
"<h2 class='footer'>ThankYou!!!Happing Coding</h2>\n" +
"\n" +
"\n" +
"</div>\n" +
"</body>\n" +
"</html>\n" +
"\n";

            try {
			File file = new File("invoice.html");
			FileWriter fileWriter = new FileWriter(file);
			fileWriter.write(str);
			fileWriter.flush();
			fileWriter.close();
		} catch (Exception e) {
          	System.out.println(e.getMessage());	
                
                }



    }//GEN-LAST:event_btnprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fee_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fee_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fee_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fee_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fee_detail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpay;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnsearch;
    private javax.swing.JTable fee_record;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtamount1;
    private javax.swing.JTextField txtcid1;
    private javax.swing.JTextField txtdate1;
    private javax.swing.JTextField txtmobile1;
    private javax.swing.JTextField txtmobile_search;
    private javax.swing.JTextField txtname1;
    private javax.swing.JTextField txtname_search;
    private javax.swing.JTextField txtsid1;
    private javax.swing.JTextField txtsid_search;
    // End of variables declaration//GEN-END:variables
}
